/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './muster-bericht.html',
    './datenquellen.html',
    './admin.html',
    './fuer-immobilienkaeufer.html',
    './fuer-gartenbesitzer.html',
    './fuer-bautraeger.html',
    './fuer-landwirte.html',
    './wissen/index.html',
    './wissen/altlast.html',
    './wissen/setzung-vs-hebung.html',
    './wissen/eu-bodenrichtlinie.html',
    './wissen/schwermetalle-im-boden.html',
    './wissen/insar-egms.html',
    './wissen/hochwasser-risikoklasse.html',
    './wissen/bbodschv.html',
    './wissen/erosion-rusle.html',
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
        },
        navy: {
          50: '#f0f4ff',
          100: '#dbe4ff',
          200: '#bac8ff',
          300: '#91a7ff',
          400: '#748ffc',
          500: '#5c7cfa',
          600: '#4c6ef5',
          700: '#1a3a6b',
          800: '#122b52',
          900: '#0c1d3a',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
